# Generated by Django 5.0.1 on 2024-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('moneda', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('fecha_apertura', models.DateField()),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('cci', models.CharField(max_length=20)),
                ('funcionario', models.CharField(max_length=100)),
                ('agencia_apertura', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
